"""empty message

Revision ID: 06917189b262
Revises: 
Create Date: 2018-10-26 12:39:28.813966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06917189b262'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('awards', 'award_news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('award_news', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
