"""empty message

Revision ID: 7978443e45a1
Revises: df088cf4ecad
Create Date: 2018-11-04 14:41:19.098441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7978443e45a1'
down_revision = 'df088cf4ecad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicknumber', sa.Column('cha_clicks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clicknumber', 'cha_clicks')
    # ### end Alembic commands ###
