"""empty message

Revision ID: 9f7185eed978
Revises: c2d5fcf9569b
Create Date: 2018-10-28 15:46:34.173589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f7185eed978'
down_revision = 'c2d5fcf9569b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_awards')
    op.add_column('awards', sa.Column('awardTitle', sa.String(length=100), nullable=True))
    op.drop_column('awards', 'award_title')
    op.drop_column('awards', 'award_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('award_time', mysql.DATETIME(), nullable=True))
    op.add_column('awards', sa.Column('award_title', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('awards', 'awardTitle')
    op.create_table('user_awards',
    sa.Column('awards_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_messages_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['awards_id'], ['awards.id'], name='user_awards_ibfk_1'),
    sa.ForeignKeyConstraint(['user_messages_id'], ['user_messages.id'], name='user_awards_ibfk_2'),
    sa.PrimaryKeyConstraint('awards_id', 'user_messages_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
