"""empty message

Revision ID: c2d5fcf9569b
Revises: 06917189b262
Create Date: 2018-10-26 15:02:44.816910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2d5fcf9569b'
down_revision = '06917189b262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('awardId', sa.Integer(), nullable=True))
    op.drop_column('awards', 'award_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('award_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('awards', 'awardId')
    # ### end Alembic commands ###
